language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - master
before_script:
   - npm start
   - sleep 3
script:
   - npm test
after_script:
   - npm stop
