module.exports = {
  getPostsForPage: getPostsForPage,
  getPostByTitle: getPostByTitle
};

/**
 * This method gets the posts for a given page
 */
function getPostsForPage(pageNo, postsPerPage, callback) {
  // Probably don't need to have as var but just for testing purposes cur rently
  console.log('came in')
  var err;
  var posts = getPosts();
  if (posts.length + postsPerPage < postsPerPage * pageNo) {
    err = "not found";
  }
  callback(err, posts.slice((pageNo - 1) * postsPerPage, postsPerPage * pageNo), Math.ceil(posts.length / postsPerPage));
}

function getPostByTitle(title, callback) {
  title = title.replace(/_/g, ' ');
  var post = getPosts().filter(function (item) {
    return item.title.toLowerCase() === title;
  })[0];
  if (post) {
    callback(null, post);
  } else {
    callback('not found');
  }
}

/**
 * Temp function for when i'm faking the posts
 */
function post(title, author, content, tags, timestamp) {
  return {
    content: content,
    title: title,
    author: author,
    tags: tags,
    timeStamp: timestamp
  }
}

function getPosts() {
  return [
    post('The long one10', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one9', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one8', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one7', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The long one', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in eros quis tortor sagittis ornare. Fusce molestie diam sit amet ante gravida rutrum sed sed purus. Quisque lorem massa, aliquam quis magna et, posuere elementum ante. Integer sit amet neque non ante finibus bibendum non et erat. Pellentesque consectetur porta eros non convallis. Vestibulum efficitur massa nec nisl blandit, nec faucibus nisi fringilla. Cras et vestibulum nibh. Sed tincidunt ligula diam, interdum convallis lorem ullamcorper vitae. Pellentesque et lorem dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tristique consectetur ipsum, non dictum odio faucibus ac. Curabitur quis odio nisi. Donec vulputate, lectus vitae malesuada tincidunt, lorem risus interdum sapien, ut egestas odio risus vitae nisi. Praesent sagittis justo quis risus hendrerit commodo. \n \n Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam commodo, purus in fermentum convallis, ipsum leo finibus neque, ut auctor orci purus quis arcu. Mauris vehicula lectus bibendum tortor facilisis luctus. Suspendisse et libero pulvinar, aliquet magna at, mollis est. Morbi posuere, diam in fringilla dignissim, ante dolor hendrerit nisi, ac ultrices libero turpis sed dolor. Fusce eros tellus, rhoncus at ultrices vel, euismod posuere massa. Quisque gravida ante a tellus tincidunt iaculis. Suspendisse tristique tellus quis quam viverra malesuada et venenatis sem. In hac habitasse platea dictumst. Suspendisse semper enim risus, eu commodo turpis lobortis id. Donec malesuada viverra enim, at efficitur enim ornare id. Morbi porttitor mi at porta scelerisque.', 'Dave', 'testing', '2017-06-12 13:00:00+01', '2017-06-12 13:00:00+01'),
    post('The difficult second post', 'This is going to be the second post, we are you to try new line \n with any luck it will work', 'Ben', 'second,testing', '2017-06-10 15:00:00+01', '2017-06-10 15:00:00+01'),
    post('The first post', 'This is going to be the first post we create', 'Ben', 'first,brand new,testing', '2017-06-10 13:00:00+01', '2017-06-10 13:00:00+01')
  ];
}

